# Use Travis's legacy infrastructure
sudo: required

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

# Don't `bundle install`
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
    - INSTANCE=server-runas-splunk-ubuntu-1404
    - INSTANCE=client-inputs-outputs-ubuntu-1404
    - INSTANCE=server-runas-splunk-centos-7
    - INSTANCE=client-inputs-outputs-centos-7

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  # We have to install chef-sugar for ChefSpec
  - /opt/chefdk/embedded/bin/chef gem install chef-sugar
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker
  # workaround for "unusable filesystem" error in splunk
  # https://answers.splunk.com/answers/9035/can-i-run-splunk-on-btrfs.html#answer-152672
  - sudo mkdir -p /data/splunk-test
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
